### ISSUE TITLE
Complete instances for break-through and connect-4 and gttt-4x4

### ISSUE THREAD

**Issue by hharryyf** [irfansha/Q-sage#10]
Hi Irfansha, I have read your paper Concise QBF Encodings for Games on a Grid. It's a very interesting paper. I saw in your paper, there's a table 2 for the results on HTTT, Breakthrough, and connect-4. I also saw the corresponding instances in the benchmark directory. However, I'm wondering, do you also have the full set of instances for those games? I mean for example, in connect-4 5x5, you reported the maximum refuted depth for your encoding is 11, and you provided instances of depth 11 in your benchmark directory. Is there a generator I can run in your project that could generate the QBF instance in QDIMACS format for any game (HTTT, Breakthrough, and Connect-4) at any depth?

Thanks for your reply.

**Comment by irfansha** [comment]
Hi hharryyf, thanks for reaching out.

You can indeed generate instances for any game.
We need to provide a BDDL model (as discussed in the paper). In that model, you encode the target game and specify the depth.
The models for games, HTTT, Breakthrough and Connect-4 are available in this folder : https://github.com/irfansha/Q-sage/blob/main/Benchmarks/SAT2023_GDDL.zip

For example, if you want to generate qbf instance of connect-4 for depth 13.
Once you unzip, in the folder "./GDDL_models/connect-c" you will find the corresponding domain file.
For problem file, you can use "./GDDL_models/connect-c/5x5_11_connect4.ig" but change the depth from 11 to 13 in line 5.
You can also change the board size, or initial state as described in the paper.

Once you have these input files, you can use the following command (as described in the readme file in this repository):
python3 Q-sage.py --game_type general -e bwnib --ib_domain Benchmarks/SAT2023_GDDL/GDDL_models/connect-c/domain.ig --ib_problem Benchmarks/SAT2023_GDDL/GDDL_models/connect-c/5x5_11_connect4.ig --encoding_out [path-to-out-file]

In the output file, you will get the QBF instance.

I hope this helps, please feel free to reach out if you need any more information.

**Comment by hharryyf** [comment]
Thanks for your reply. It is very helpful. I have one specific question about your encoding method, don't worry if you don't want to answer it. Based on your encoding (without bloqqer preprocessing), can the search-based QBF solvers like depqbf make illegal moves in an existential quantifier block and move on to the next quantifier block without causing some clauses to be UNSAT? Or the goal indicator variable gs^i can always stop existential quantifiers to assign some illegal actions to be true?

**Comment by irfansha** [comment]
I am glad it is helpful.
No, as far as I understand your question it is not possible.
In a search based QBF solver search, any illegal move by an existential player will result in UNSAT due to indicator variables.
Well there is some information symbollically in the inner most universal layer, so whether the solver "sees" the instance is UNSAT is not clear.

**Comment by hharryyf** [comment]
Hi, thanks a lot. I just want to confirm that my understanding is correct. Suppose the encoded instance has 9 quantifier blocks, odd levels are existential, even levels are universal. Let's call the matrix of this formula M. Then, at quantifier block 1, the existential quantifier makes an illegal move (assign an illegal action "a" to be true). Then, according to your encoding, it must be the case that M[a] (M with assigning "a" to be true) is UNSAT. However, whether M[a] can be derived to be UNSAT immediately at level 1 by unit propagation and pure literal elimination is unclear, because the illegality detection is actually done by the smart assignment of the innermost universal quantifiers, and the innermost universal quantifiers must have a way to UNSAT the instance? Therefore, it is still possible that the UNSAT conflict is reported at level 9 (after the indicator universal variables at level 8 make assignments) although the real illegal assignment happens at level 1.

**Comment by irfansha** [comment]
Hi,
Yes, that is mostly correct.
Essentially, there are 2 different ways to make an illegal move:
  1) out of bounds of board or choosing invalid action name (due to binary encoding)
  2) voilating preconditions due to previous moves.

The first case is already detected already at 1st level in your example. It does not depend on the inner most universal variables.
What you say is true in the second case, it is possible that the conflict is reported at level 9. It highly depends on the solver.
